In [2]:
!git clone https://github.com/deedGhost/HealthLearning

Cloning into 'HealthLearning'...
remote: Enumerating objects: 72, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 72 (delta 13), reused 7 (delta 7), pack-reused 53
Receiving objects: 100% (72/72), 1.07 MiB | 7.14 MiB/s, done.
Resolving deltas: 100% (15/15), done.

In [3]:
%cd HealthLearning

/content/HealthLearning

In [4]:
import pandas as pd
# Load the dataset
df = pd.read_csv("/content/HealthLearning/Cardiovascular Heart Disease/heart_data.csv")

# Display the first few rows
print(df.head())

   index  id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
0      0   0  18393       2     168    62.0    110     80            1     1
1      1   1  20228       1     156    85.0    140     90            3     1
2      2   2  18857       1     165    64.0    130     70            3     1
3      3   3  17623       2     169    82.0    150    100            1     1
4      4   4  17474       1     156    56.0    100     60            1     1

   smoke  alco  active  cardio
0      0     0       1       0
1      0     0       1       1
2      0     0       0       1
3      0     0       1       1
4      0     0       0       0

In [5]:
features = df.columns[:-1]  # Assuming the last column is the label
labels = df.columns[-1]      # Assuming the last column is the label
print("Features:", features)
print("Labels:", labels)

Features: Index(['index', 'id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo',
       'cholesterol', 'gluc', 'smoke', 'alco', 'active'],
      dtype='object')
Labels: cardio

In [6]:
# Explore size and shape
num_rows, num_cols = df.shape
print("Number of rows:", num_rows)
print("Number of columns:", num_cols)

Number of rows: 70000
Number of columns: 14

In [7]:
# Check for missing values & data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        70000 non-null  int64
 1   id           70000 non-null  int64
 2   age          70000 non-null  int64
 3   gender       70000 non-null  int64
 4   height       70000 non-null  int64
 5   weight       70000 non-null  float64
 6   ap_hi        70000 non-null  int64
 7   ap_lo        70000 non-null  int64
 8   cholesterol  70000 non-null  int64
 9   gluc         70000 non-null  int64
 10  smoke        70000 non-null  int64
 11  alco         70000 non-null  int64
 12  active       70000 non-null  int64
 13  cardio       70000 non-null  int64
dtypes: float64(1), int64(13)
memory usage: 7.5 MB

In [8]:
df.describe()

,index,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,34999.500000,49972.419900,19468.865814,1.349571,164.359229,74.205690,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,20207.403759,28851.302323,2467.251667,0.476838,8.210126,14.395757,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,0.000000,10798.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,17499.750000,25006.750000,17664.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,34999.500000,50001.500000,19703.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,52499.250000,74889.250000,21327.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,69999.000000,99999.000000,23713.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
df.memory_usage()

Index             128
index          560000
id             560000
age            560000
gender         560000
height         560000
weight         560000
ap_hi          560000
ap_lo          560000
cholesterol    560000
gluc           560000
smoke          560000
alco           560000
active         560000
cardio         560000
dtype: int64

In [10]:
# Converting the units of the age column from days to years
df['age'] = df['age'] / 365.25

# Cleaning dataset to filter out erroneous values of ap_hi and ap_lo
# Calculate BMI
df["bmi"] = df["weight"] / ((df["height"] / 100) * (df["height"] / 100))

# Filter out erroneous values of ap_hi and ap_lo
df = df[(df["ap_hi"] < 200) & (df["ap_hi"] > 50) & (df["ap_lo"] < 200) & (df["ap_lo"] > 50)]
# Filter out erroneous values of BMI
df = df[(df["bmi"] < 40) & (df["bmi"] > 10)]

# Drop the "index" column
df = df.drop("index", axis=1)
# Set the "id" column as the new index
df = df.set_index("id")

## Criteria for Selecting Marginal Values as 50 and 200:
These thresholds for ap_low and ap_hi as are chosen based on typical ranges for blood pressure readings in adults and are aimed at filtering out extreme values and impossible measurements while retaining a reasonable range within the dataset.

In [11]:
df.describe()

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,bmi
count,66749.000000,66749.000000,66749.000000,66749.000000,66749.000000,66749.000000,66749.000000,66749.000000,66749.000000,66749.000000,66749.000000,66749.000000,66749.000000
mean,53.267292,1.354282,164.571065,73.117618,126.196797,81.217082,1.356889,1.220767,0.088765,0.053409,0.804117,0.489311,27.008279
std,6.762636,0.478299,7.809218,12.791810,16.190805,9.416065,0.672890,0.566762,0.284407,0.224849,0.396882,0.499889,4.457495
min,29.563313,1.000000,120.000000,28.000000,70.000000,52.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,10.726644
25%,48.309377,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,23.828125
50%,53.924709,1.000000,165.000000,71.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,26.175195
75%,58.368241,2.000000,170.000000,81.000000,140.000000,90.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,29.752066
max,64.922656,2.000000,250.000000,135.000000,197.000000,190.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,39.965649

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66749 entries, 0 to 99999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          66749 non-null  float64
 1   gender       66749 non-null  int64
 2   height       66749 non-null  int64
 3   weight       66749 non-null  float64
 4   ap_hi        66749 non-null  int64
 5   ap_lo        66749 non-null  int64
 6   cholesterol  66749 non-null  int64
 7   gluc         66749 non-null  int64
 8   smoke        66749 non-null  int64
 9   alco         66749 non-null  int64
 10  active       66749 non-null  int64
 11  cardio       66749 non-null  int64
 12  bmi          66749 non-null  float64
dtypes: float64(3), int64(10)
memory usage: 7.1 MB

In [13]:
df.memory_usage()

Index          533992
age            533992
gender         533992
height         533992
weight         533992
ap_hi          533992
ap_lo          533992
cholesterol    533992
gluc           533992
smoke          533992
alco           533992
active         533992
cardio         533992
bmi            533992
dtype: int64